name: Build Centos Image
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  build:
    # Job name is Greeting
    name: Docker Build

    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Docker Build
        run: docker build -t my-centos .
      - name: Docker Start Process
        run: docker run --name fs -it -d my-centos
      - name: Docker Export File System
        run: docker export --output my-centos.tar fs
      - name: Docker Stop Process
        run: docker stop wsl
      - name: Docker Remove Process
        run: docker rm wsl
      - name: Publish WSL Distribution
        uses: actions/upload-artifact@v1
        with:
          name: Publish server
          path: my-centos.tar
